---
- name: 1. Install Apache
  become: true
  apt: name=apache2 state=present update_cache=yes
- name: 2. Install PHP Module
  apt: name=libapache2-mod-php state=present
- name: 3. Start Apache
  service: name=apache2 state=started enabled=yes
- name: 4. Install Hello World PHP Script
  copy: src=index.php dest=/var/www/html/index.php mode=0664 
